### ISSUE TITLE
Tab completion should expand endpoint aliases

### ISSUE THREAD

**Issue by marians** [giantswarm/gsctl#243] opened 2018-06-29 09:30 UTC
When I enter a command that needs an endpoint alias, it would be nice if the alias would be completed automatically.

Example:

```
gsctl sel<tab> en<tab> go<tab>
```

expands to

```
gsctl select endpoint gollum
```

**Comment by axbarsan** [comment] 2020-03-06 12:11
Closed because it is a duplicate of https://github.com/giantswarm/gsctl/issues/159 , which has been fixed

**Closed by axbarsan** 2020-03-06 12:11 UTC
Labels: topic/completion
