### ISSUE TITLE
Allow setting api-endpoint in config file

### ISSUE THREAD

**Issue by r7vme** [giantswarm/gsctl#104] opened 2017-07-18 11:15 UTC
### What did you do/observe?

Currently i need to use ` gsctl --api-endpoint=https://api.foo.bar <COMMAND>` if i want to access non default endpoint.

### What did you expect?

I want to setup api-endpoint in config file and use like `gsctl <COMMAND>`

### Details

- Operating system, platform/architecture: All
- Output of `gsctl version`: 0.6.0
- Any other details required to reproduce the problem: No

**Comment by nikhuber** [comment] 2017-09-11 09:20
+1

**Comment by marians** [comment] 2017-09-26 11:23
Closing as duplicate of https://github.com/giantswarm/gsctl/issues/47

**Closed by marians** 2017-09-26 11:23 UTC
Labels: config, UX
